// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7fXhkRsnE1K4mjzJvY-pdF4C-aUTd2u8',
    appId: '1:198062077802:web:cc51bbe6a6a75480f71713',
    messagingSenderId: '198062077802',
    projectId: 'fitness-tracker-app-4134b',
    authDomain: 'fitness-tracker-app-4134b.firebaseapp.com',
    databaseURL: 'https://fitness-tracker-app-4134b-default-rtdb.firebaseio.com',
    storageBucket: 'fitness-tracker-app-4134b.appspot.com',
    measurementId: 'G-B8WZ3WS24B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeYVGoFQzPzyY5QMZgxZ2i5Q4uGAB0z3c',
    appId: '1:198062077802:android:436740366ca20d54f71713',
    messagingSenderId: '198062077802',
    projectId: 'fitness-tracker-app-4134b',
    databaseURL: 'https://fitness-tracker-app-4134b-default-rtdb.firebaseio.com',
    storageBucket: 'fitness-tracker-app-4134b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbXjMilQwYG-DGMf_iAK2ZBE80xy5eXIQ',
    appId: '1:198062077802:ios:9a2e64625ba5818ef71713',
    messagingSenderId: '198062077802',
    projectId: 'fitness-tracker-app-4134b',
    databaseURL: 'https://fitness-tracker-app-4134b-default-rtdb.firebaseio.com',
    storageBucket: 'fitness-tracker-app-4134b.appspot.com',
    iosBundleId: 'com.example.fitnessTrackerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbXjMilQwYG-DGMf_iAK2ZBE80xy5eXIQ',
    appId: '1:198062077802:ios:5a2f74d34694a878f71713',
    messagingSenderId: '198062077802',
    projectId: 'fitness-tracker-app-4134b',
    databaseURL: 'https://fitness-tracker-app-4134b-default-rtdb.firebaseio.com',
    storageBucket: 'fitness-tracker-app-4134b.appspot.com',
    iosBundleId: 'com.example.fitnessTrackerApp.RunnerTests',
  );
}
